-- MySQL Script generated by MySQL Workbench
-- Mon Apr 15 19:54:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa` DEFAULT CHARACTER SET utf8 ;
USE `empresa` ;

-- -----------------------------------------------------
-- Table `empresa`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`Categoria` (
  `Codigo` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`Documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`Documentos` (
  `Codigo_documentos` INT NOT NULL,
  `Categoria_Codigo` INT NOT NULL,
  PRIMARY KEY (`Codigo_documentos`),
  INDEX `fk_Documentos_Categoria_idx` (`Categoria_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Documentos_Categoria`
    FOREIGN KEY (`Categoria_Codigo`)
    REFERENCES `empresa`.`Categoria` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`Fisico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`Fisico` (
  `Codigo_documentos` INT NOT NULL,
  `Devolucion` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo_documentos`),
  CONSTRAINT `fk_Fisico_Documentos1`
    FOREIGN KEY (`Codigo_documentos`)
    REFERENCES `empresa`.`Documentos` (`Codigo_documentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`Digital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`Digital` (
  `Codigo_documentos` INT NOT NULL,
  `direccion_descarga` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo_documentos`),
  CONSTRAINT `fk_Digital_Documentos1`
    FOREIGN KEY (`Codigo_documentos`)
    REFERENCES `empresa`.`Documentos` (`Codigo_documentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`Usuario` (
  `NIF` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`NIF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`Registrados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`Registrados` (
  `Usuario_NIF` INT NOT NULL,
  `fecha_alta` DATE NULL,
  `total_prestamos` VARCHAR(45) NULL,
  PRIMARY KEY (`Usuario_NIF`),
  CONSTRAINT `fk_Registrados_Usuario1`
    FOREIGN KEY (`Usuario_NIF`)
    REFERENCES `empresa`.`Usuario` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`Administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`Administradores` (
  `Usuario_NIF` INT NOT NULL,
  `horario` VARCHAR(45) NULL,
  `Sustituye` INT NOT NULL,
  PRIMARY KEY (`Usuario_NIF`),
  INDEX `fk_Administradores_Administradores1_idx` (`Sustituye` ASC) VISIBLE,
  CONSTRAINT `fk_Administradores_Usuario1`
    FOREIGN KEY (`Usuario_NIF`)
    REFERENCES `empresa`.`Usuario` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Administradores_Administradores1`
    FOREIGN KEY (`Sustituye`)
    REFERENCES `empresa`.`Administradores` (`Usuario_NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`Prestamo` (
  `Documentos_Codigo_documentos` INT NOT NULL,
  `Usuario_NIF` INT NOT NULL,
  `fecha_prestamo` DATE NULL,
  `hora_prestamo` TIME NULL,
  `fecha_devolucion` DATE NULL,
  PRIMARY KEY (`Documentos_Codigo_documentos`, `Usuario_NIF`),
  INDEX `fk_Documentos_has_Usuario_Usuario1_idx` (`Usuario_NIF` ASC) VISIBLE,
  INDEX `fk_Documentos_has_Usuario_Documentos1_idx` (`Documentos_Codigo_documentos` ASC) VISIBLE,
  CONSTRAINT `fk_Documentos_has_Usuario_Documentos1`
    FOREIGN KEY (`Documentos_Codigo_documentos`)
    REFERENCES `empresa`.`Documentos` (`Codigo_documentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Documentos_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_NIF`)
    REFERENCES `empresa`.`Usuario` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`Sustituye`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`Sustituye` (
  `Documentos_Codigo_documentos` INT NOT NULL,
  `Documentos_Codigo_documentos1` INT NOT NULL,
  PRIMARY KEY (`Documentos_Codigo_documentos`, `Documentos_Codigo_documentos1`),
  INDEX `fk_Documentos_has_Documentos_Documentos2_idx` (`Documentos_Codigo_documentos1` ASC) VISIBLE,
  INDEX `fk_Documentos_has_Documentos_Documentos1_idx` (`Documentos_Codigo_documentos` ASC) VISIBLE,
  CONSTRAINT `fk_Documentos_has_Documentos_Documentos1`
    FOREIGN KEY (`Documentos_Codigo_documentos`)
    REFERENCES `empresa`.`Documentos` (`Codigo_documentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Documentos_has_Documentos_Documentos2`
    FOREIGN KEY (`Documentos_Codigo_documentos1`)
    REFERENCES `empresa`.`Documentos` (`Codigo_documentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
